name: Where Jason Thompson thinks out loud 
markdown: kramdown 
exclude: [Guardfile]
pygments: true
timezone: Canada/Eastern
permalink: /:year/:month/:title
paginate: 5
tag_dir: 'topics'
date_archive:
  path: /archive/
